### PR TITLE
Add HttpResponse in the Response struct so we can support custom Endp…

### PR DESCRIPTION
**Pull request by tgracchus**
…ointHandlers and Proxies able to simple forward the response: for example when downloading binary content

### CODE REVIEW

**Comment by kpacha** [comment]
Hi, @tgracchus !

First of all, thanks for the contribution. I didn't think about this particular requirement and it's quite challenging.

After checking the current implementation of your proposal, I have some questions/comments:

1. What's the idea behind the addition of the `Var` struct?  If we need a way to pass extra vars to some component, maybe we should use a more agnostic and extensible implementation with namespaces or something like that. Maybe we could use a simple interface for a getter function, inject the required implementations at building time (before parsing the config file), store the getters in a map and expose that map of getters to the components. Every module would check if its required getter is available and consume the extra variables (and there will be fewer limitations to the kind of data these extra var could contain). The config data is required just at building time, so all the safety checks we use here when casting interfaces won't affect the performance nor the stability of the project.

2. Adding a `*http.Response` to the `proxy.Response` struct will couple the transport layer with the proxy through the `net/http` implementation. That's why the `proxy` package has a `http.go` file, because the components defined in that file are not tied to the rest of the package and can be replaced with any other implementation (i.e.: github.com/valyala/fasthttp) or transport (i.e.: amqp). Maybe we can add two more general structs: a metadata map and a *io.Reader. With these params, I think we can deal with the use case you're describing and keep the krakend framework as agnostic as possible.

BTW, if you create a different PR for the minor fixes you added to the `proxy` package, I'll merge them ASAP.

cheers!

**Comment by tgracchus** [comment]
Hello,

Thank you for the warm welcome. 
Also your comments are appreciated.
Let's go to business now!!

1. The idea is to add some way to provided the Factory interface with some extra configuration, not just the standard one, in order to support different Proxy Implementations.
https://github.com/devopsfaith/krakend/blob/master/proxy/factory.go#L14
Also, the same idea applies to the EndpointHandler function
https://github.com/devopsfaith/krakend/blob/10b3e7b787004d282b57d7367864d629eecf96eb/router/gin/endpoint.go#L25

Both cases are needed in our use case of forwarding the contest of the response from the proxy to the endpoint 

2. Ok, seems very reasonable.
iIf I understand your well. Do you mean to add a metadata field and an io.ReadCloser field to the response struct? To have the headers and the raw input stream from the response?

**Comment by kpacha** [comment]
Hi!

I like the changes you made in the config package. It feels more flexible this way.

Let's keep the discussion in two parts:

1. OK, that was what I though. Also, I was suggesting the extra getter function so proxy factories and proxy components are not required to know how to parse the raw config values themselves. They just cast the received interface. If my component `namespace.A` requires some extra data, I think it's reasonable to create a `namespace.AConfigGetter` function implementing the required logic, link them to the namespace of the component `A` somewhere in the `config` package and use it for accessing the extra data. It's also reasonable to provide a default implementation in the `config` package, for those custom implementations that don't require any fancy manipulation of the data and are ok getting a `map[string]interface{}`. That would open the door to very powerful components with very particular requirements, such as:
+ using a custom DSL for complex rules enforced by a custom proxy component (i.e.: time filter middleware, ACL, etc)
+ linking a directory and scanning it with the config getter in order to get some certificates to use in the communication with a set of backend instances
+ composing some sophisticated filter and manipulation proxy layer supporting all sorts of interesting stuff beyond the limits of the default ones (bounded by the [krakend rules](https://github.com/devopsfaith/krakend/blob/master/docs/OVERVIEW.md#the-krakend-rules) and our performance-first mindset).

2. Yes, that was my point. Are you aware of any other possible requirement? Should we enforce the stream to implement the `io.ReadCloser` interface instead of the simpler `io.Reader`? That will match very well with the `http.Response` but I'm not sure that will be required for other transport layers or implementations (i.e.: https://godoc.org/github.com/valyala/fasthttp#Response)

cheers!

**Comment by tgracchus** [comment]
Hello,

I pushed some new changes.

1. There's a new interface ConfigGetter with a default implementation: DefaultConfigGetter.
It returns a interface so the Proxy or EndpointHandler sould cast it to the expected struct.
Is that what you mean?

2. Add two new fields to response: one for metadata and other for reader.
About io.ReadClose. We need to stream the response, so once it's retransmitted to the client in the EndpointHandler we need to close the connection.
That's the reason we might need the Close method.
What do you think about it?

Thanks

**Comment by kpacha** [comment]
Hi,

1. I was thinking something like this:

```
package config

type ExtraConfiguration map[string]interface{}

type ConfigGetter func(ExtraConfiguration) interface{}

func DefaultConfigGetter(extra ExtraConfiguration) interface{} { return extra }

const defaultNamespace = "github.com/devopsfaith/krakend/config"

var ConfigGetters = map[string]ConfigGetter{defaultNamespace: DefaultConfigGetter}
```
and this kind of implementations:
```
package config

import (
	"testing"
	"time"
)

func TestDefaultConfigGetter(t *testing.T) {
	getter, ok := ConfigGetters[defaultNamespace]
	if !ok {
		t.Error("Nothing stored at the default namespace")
		return
	}
	extra := ExtraConfiguration{
		"a": 1,
		"b": true,
		"c": []int{1, 1, 2, 3, 5, 8},
	}
	result := getter(extra)
	res, ok := result.(ExtraConfiguration)
	if !ok {
		t.Error("error casting the returned value")
		return
	}
	if v, ok := res["a"]; !ok || 1 != v.(int) {
		t.Errorf("unexpected value for key `a`: %v", v)
		return
	}
	if v, ok := res["b"]; !ok || !v.(bool) {
		t.Errorf("unexpected value for key `b`: %v", v)
		return
	}
	if v, ok := res["c"]; !ok || 6 != len(v.([]int)) {
		t.Errorf("unexpected value for key `c`: %v", v)
		return
	}
}

func TestConfigGetter(t *testing.T) {
	ConfigGetters = map[string]ConfigGetter{
		"ns1": func(e ExtraConfiguration) interface{} {
			return len(e)
		},
		"ns2": func(e ExtraConfiguration) interface{} {
			v, ok := e["publishedAt"]
			if !ok {
				return e
			}
			start, ok := v.(time.Time)
			if !ok {
				return e
			}
			if start.After(time.Now()) {
				return nil
			}
			return e
		},
	}
	extra := ExtraConfiguration{
		"a": 1,
		"b": true,
		"c": []int{1, 1, 2, 3, 5, 8},
	}

	tmp1 := ConfigGetters["ns1"](extra)
	v, ok := tmp1.(int)
	if !ok {
		t.Error("error casting the returned value")
		return
	}
	if 3 != v {
		t.Errorf("unexpected value for getter `ns1`: %v", v)
		return
	}

	tmp2 := ConfigGetters["ns2"](extra)
	res, ok := tmp2.(ExtraConfiguration)
	if !ok {
		t.Error("error casting the returned value")
		return
	}
	if v, ok := res["a"]; !ok || 1 != v.(int) {
		t.Errorf("unexpected value for key `a`: %v", v)
		return
	}
	if v, ok := res["b"]; !ok || !v.(bool) {
		t.Errorf("unexpected value for key `b`: %v", v)
		return
	}
	if v, ok := res["c"]; !ok || 6 != len(v.([]int)) {
		t.Errorf("unexpected value for key `c`: %v", v)
		return
	}
}
```
It's not great but it defines a system that covers all the current requirements and it's open for future extensions. Notice I went back to the `ExtraConfig` struct in order to avoid using any basic type directly. Also, I'd rather use a typed function instead of a complete interface for the `ConfigGetter` because its implementation requires less boilerplate code.

2. Here, I have two comments:

* Since the properties are exported, the accessors aren't required (I'm talking about `GetInputStream()` and `GetMetadata()`).
* I'm not comfortable requesting the `io.Closer` interface for the entire system just because a single use case. Maybe we should add a wrapper over the `Body` of the `net/http` response and delegate the closing to it.

cheers!

**Comment by tgracchus** [comment]
Hi

1. Added

2. Not sure how to wrap it.
At some point we need to close the stream. If we only have a Read method and for some reason and there's an error delivering back the response, just an example, we need to close the response, no exhaust all the remaining data.
I do not see how to achieve this without a dedicated method
What do you think about it?

**Comment by kpacha** [comment]
:thinking: 

Crazy idea: add a context to the wrapper factory/builder and cancel it whenever you're done. The context status could be monitored inside the wrapper, making it transparent for the client. This response context could depend on the request one and I think everything will work like a charm without requiring any extra effort

What do you think?

**Comment by tgracchus** [comment]
Agree with that, I like the approach!!
I will implement it and come back

**Comment by kpacha** [comment]
Hi!

what do you think about this sample implementation?

```
func NewReadCloserWrapper(ctx context.Context, rc io.ReadCloser) io.Reader {
	w := readCloserWrapper{ctx, rc}
	go w.closeOnCancel()
	return w
}

type readCloserWrapper struct {
	ctx context.Context
	rc  io.ReadCloser
}

func (w readCloserWrapper) Read(b []byte) (int, error) {
	return w.rc.Read(b)
}

func (w readCloserWrapper) closeOnCancel() {
	<-w.ctx.Done()
	w.rc.Close()
}
```
I'm trying to evaluate the impact of the extra goroutine for each `net/http` connection because I don't want to affect the performance of the only transfer layer adapter the framework integrates so far.

**Comment by tgracchus** [comment]
I guess we will need a custom interface. Somehow we also need the cancel function to be passed to EndpointHandler

func TestResponseStream_ok(t *testing.T) {
	in := mockCloser{bytes.NewReader([]byte("Hello World!!"))}

	var cancel context.CancelFunc
	streamContext := context.Background()
	streamContext, cancel = context.WithCancel(streamContext)

	stream := NewReadCloserWrapper(streamContext, in)
	buf := new(bytes.Buffer)
	buf.ReadFrom(stream)
	s := buf.String()
	println(s)

	cancel()

}

It's working, but, The cancel function will stay in the Proxy, it will not reach the EndpointHandler

**Comment by tgracchus** [comment]
```
// Response is the entity returned by the proxy
type Response struct {
	Data       map[string]interface{}
	IsComplete bool
	Metadata   map[string]string
	stream     io.Reader
}

type Stream interface {
	read() (io.Reader, context.CancelFunc)
}

type StreamWrapper struct {
	cancel context.CancelFunc
	reader io.Reader
}

func NewStream(reader io.ReadCloser) (Stream) {
	var cancel context.CancelFunc
	streamContext := context.Background()
	streamContext, cancel = context.WithCancel(streamContext)
	stream := newReadCloserWrapper(streamContext, reader)
	return StreamWrapper{cancel, stream}
}

func (streamWrapper StreamWrapper) read() (io.Reader, context.CancelFunc) {
	return streamWrapper.reader, streamWrapper.cancel
}

type readCloserWrapper struct {
	ctx context.Context
	rc  io.ReadCloser
}

func newReadCloserWrapper(ctx context.Context, in io.ReadCloser) io.Reader {
	wrapper := readCloserWrapper{ctx, in}
	go wrapper.closeOnCancel()
	return wrapper
}

func (w readCloserWrapper) Read(b []byte) (int, error) {
	return w.rc.Read(b)
}

func (w readCloserWrapper) closeOnCancel() {
	<-w.ctx.Done()
	w.rc.Close()
}
```

```
func TestResponseStream_ok(t *testing.T) {
	in := mockCloser{bytes.NewReader([]byte("Hello World!!"))}

	var cancel context.CancelFunc

	stream := NewStream(in)
	reader, cancel := stream.read()
	buf := new(bytes.Buffer)
	buf.ReadFrom(reader)
	s := buf.String()
	println(s)

	cancel()

}
```

**Comment by kpacha** [comment]
hi,

using `context.Background()` is just an implementation detail of the test. In the KrakenD framework, every request creates its own scoped context (https://github.com/devopsfaith/krakend/blob/master/router/gin/endpoint.go#L29) derived from the global one (the one use to stop the router) and injects the new scope into the proxy chain. Every element of the chain could also create its own context and pass it to the next element. As the official doc says: 

> When a Context is canceled, all Contexts derived from it are also canceled.

so you can cancel the context at any level and the wrapper will be closed because its scope derivates from the all the others. you don't need to pass back the cancel function for that context.

in other words: the proxy pipe is just a set of wrappers changing the input, the output and/or the context of the connection to a backend and this wrapper should be created at the most internal layer of that collection of middlewares

```
func TestWrapper(t *testing.T) {
	expected := "supu"
	closed := false
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	r := NewReadCloserWrapper(ctx, dummyRC{bytes.NewBufferString(expected), &closed})
	var out bytes.Buffer
	tot, err := out.ReadFrom(r)
	if err != nil {
		t.Errorf("Total bits read: %d. Err: %s", tot, err.Error())
		return
	}
	if closed {
		t.Error("The subject shouldn't be closed yet")
		return
	}
	if tot != 4 {
		t.Errorf("Unexpected number of bits read: %d", tot)
		return
	}
	if v := out.String(); v != expected {
		t.Errorf("Unexpected content: %s", v)
		return
	}

	cancel()
	<-time.After(100 * time.Millisecond)
	if !closed {
		t.Error("The subject should be already closed")
		return
	}
}

type dummyRC struct {
	r      io.Reader
	closed *bool
}

func (d dummyRC) Read(b []byte) (int, error) {
	if *(d.closed) {
		return -1, fmt.Errorf("Reading from a closed source")
	}
	return d.r.Read(b)
}

func (d dummyRC) Close() error {
	*(d.closed) = true
	return nil
}
```

**Comment by tgracchus** [comment]
Ok, 
plz, check new version

**Comment by kpacha** [comment]
Yes, it looks like it will do the job.

Do you have any proposal for the `proxy.BackendFactory` required for injecting the wrapper?

**Comment by tgracchus** [comment]
Yes, somehting like this?

But, What if we create another PR for this?
```
// EndpointHandler implements the HandleFactory interface
func StreamEndpointHandler(configuration *config.EndpointConfig, proxy proxy.Proxy) gin.HandlerFunc {
	endpointTimeout := time.Duration(configuration.Timeout) * time.Millisecond
	return func(c *gin.Context) {
		requestCtx, cancel := context.WithTimeout(c, endpointTimeout)

		c.Header(core.KrakendHeaderName, core.KrakendHeaderValue)

		response, err := proxy(requestCtx, NewRequest(c, configuration.QueryString))
		if err != nil {
			c.AbortWithError(http.StatusInternalServerError, err)
			cancel()
			return
		}

		select {
		case <-requestCtx.Done():
			c.AbortWithError(http.StatusInternalServerError, ErrInternalError)
			cancel()
		default:
		}

		if response == nil {
			return
		}

		maxAge := int(configuration.CacheTTL.Seconds())
		maxAgeHeader := fmt.Sprintf("public, max-age=%d", maxAge)

		headers := response.Metadata
		for k := range headers {
			c.Header(k, headers[k])
		}

		if maxAge != 0 {
			c.Header("Cache-Control", maxAgeHeader)
		}
		inputStream := response.Io
		io.Copy(c.Writer, inputStream)
		cancel()
	}
}
```

**Comment by kpacha** [comment]
great!

let's close this and move the remaining 'debates' to new issues or PRs

**Pull request merged**
