### PR TITLE
#184 added httptreemux router adapter

### PR DESCRIPTION
**Pull request by Foxcool**

### CODE REVIEW

**Comment by Foxcool** [comment]
now is WIP. No merge (:

**Comment by Foxcool** [comment]
WIP!
no merge (:

**Comment by Foxcool** [comment]
Possible problem: not working status code transit (on demand)

**Comment by kpacha** [comment]
@Foxcool , before merging, it would be nice to add the new router to the integration test suite. Here you have an example: https://github.com/devopsfaith/krakend/blob/master/test/integration_test.go#L40:L49

**Comment by kpacha** [comment]
@Foxcool , please remember to remove the `WIP` tag when ready.

Also, don't forget to upgrade the `dep` by adding the new dependencies to the Gopkg.toml

**Comment by taik0** [comment]
Hi @Foxcool I think you are using an older version of `dep`. You need to use 0.5

**Pull request merged**
